const countryStateData: Record<string, string[]> = {
  // United States
  USA: [
    "AL",
    "AK",
    "AZ",
    "AR",
    "CA",
    "CO",
    "CT",
    "DE",
    "FL",
    "GA",
    "HI",
    "ID",
    "IL",
    "IN",
    "IA",
    "KS",
    "KY",
    "LA",
    "ME",
    "MD",
    "MA",
    "MI",
    "MN",
    "MS",
    "MO",
    "MT",
    "NE",
    "NV",
    "NH",
    "NJ",
    "NM",
    "NY",
    "NC",
    "ND",
    "OH",
    "OK",
    "OR",
    "PA",
    "RI",
    "SC",
    "SD",
    "TN",
    "TX",
    "UT",
    "VT",
    "VA",
    "WA",
    "WV",
    "WI",
    "WY",
  ],

  // Canada
  CAN: [
    "AB",
    "BC",
    "MB",
    "NB",
    "NL",
    "NS",
    "NT",
    "NU",
    "ON",
    "PE",
    "QC",
    "SK",
    "YT",
  ],

  // Australia
  AUS: ["ACT", "NSW", "NT", "QLD", "SA", "TAS", "VIC", "WA"],

  // India (states & union territories)
  IND: [
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
    "Andaman & Nicobar",
    "Chandigarh",
    "Dadra & Nagar Haveli",
    "Daman & Diu",
    "Delhi",
    "Jammu & Kashmir",
    "Ladakh",
    "Lakshadweep",
    "Puducherry",
  ],

  // Mexico
  MEX: [
    "AGU",
    "BCN",
    "BCS",
    "CAM",
    "CHP",
    "CHH",
    "COA",
    "COL",
    "DUR",
    "GUA",
    "GRO",
    "HID",
    "JAL",
    "MEX",
    "MIC",
    "MOR",
    "NAY",
    "NL",
    "OAX",
    "PUE",
    "QUE",
    "ROO",
    "SLP",
    "SIN",
    "SON",
    "TAB",
    "TAM",
    "TLA",
    "VER",
    "YUC",
    "ZAC",
  ],

  // Brazil
  BRA: [
    "AC",
    "AL",
    "AP",
    "AM",
    "BA",
    "CE",
    "DF",
    "ES",
    "GO",
    "MA",
    "MT",
    "MS",
    "MG",
    "PA",
    "PB",
    "PR",
    "PE",
    "PI",
    "RJ",
    "RN",
    "RS",
    "RO",
    "RR",
    "SC",
    "SP",
    "SE",
    "TO",
  ],

  // Germany (Bundesländer)
  DEU: [
    "BW",
    "BY",
    "BE",
    "BB",
    "HB",
    "HH",
    "HE",
    "MV",
    "NI",
    "NW",
    "RP",
    "SL",
    "SN",
    "ST",
    "SH",
    "TH",
  ],

  // France (regions)
  FRA: [
    "Auvergne-Rhône-Alpes",
    "Bourgogne-Franche-Comté",
    "Bretagne",
    "Centre-Val de Loire",
    "Corse",
    "Grand Est",
    "Guadeloupe",
    "Guyane",
    "Hauts-de-France",
    "Île-de-France",
    "Martinique",
    "Mayotte",
    "Normandie",
    "Nouvelle-Aquitaine",
    "Occitanie",
    "Pays de la Loire",
    "Provence-Alpes-Côte d'Azur",
    "La Réunion",
  ],

  // United Kingdom (countries)
  GBR: ["England", "Northern Ireland", "Scotland", "Wales"],

  // Italy (regions)
  ITA: [
    "Abruzzo",
    "Basilicata",
    "Calabria",
    "Campania",
    "Emilia-Romagna",
    "Friuli-Venezia Giulia",
    "Lazio",
    "Liguria",
    "Lombardia",
    "Marche",
    "Molise",
    "Piemonte",
    "Puglia",
    "Sardegna",
    "Sicilia",
    "Toscana",
    "Trentino-Alto Adige",
    "Umbria",
    "Valle d'Aosta",
    "Veneto",
  ],

  // Spain (autonomous communities)
  ESP: [
    "Andalucía",
    "Aragón",
    "Asturias",
    "Baleares",
    "Canarias",
    "Cantabria",
    "Castilla-La Mancha",
    "Castilla y León",
    "Cataluña",
    "Comunidad Valenciana",
    "Extremadura",
    "Galicia",
    "La Rioja",
    "Madrid",
    "Murcia",
    "Navarra",
    "País Vasco",
  ],

  // Japan (prefectures)
  JPN: [
    "Hokkaido",
    "Aomori",
    "Iwate",
    "Miyagi",
    "Akita",
    "Yamagata",
    "Fukushima",
    "Ibaraki",
    "Tochigi",
    "Gunma",
    "Saitama",
    "Chiba",
    "Tokyo",
    "Kanagawa",
    "Niigata",
    "Toyama",
    "Ishikawa",
    "Fukui",
    "Yamanashi",
    "Nagano",
    "Gifu",
    "Shizuoka",
    "Aichi",
    "Mie",
    "Shiga",
    "Kyoto",
    "Osaka",
    "Hyōgo",
    "Nara",
    "Wakayama",
    "Tottori",
    "Shimane",
    "Okayama",
    "Hiroshima",
    "Yamaguchi",
    "Tokushima",
    "Kagawa",
    "Ehime",
    "Kōchi",
    "Fukuoka",
    "Saga",
    "Nagasaki",
    "Kumamoto",
    "Ōita",
    "Miyazaki",
    "Kagoshima",
    "Okinawa",
  ],

  // China (provinces, municipalities, SARs)
  CHN: [
    "Anhui",
    "Beijing",
    "Chongqing",
    "Fujian",
    "Gansu",
    "Guangdong",
    "Guangxi",
    "Guizhou",
    "Hainan",
    "Hebei",
    "Heilongjiang",
    "Henan",
    "Hong Kong",
    "Hubei",
    "Hunan",
    "Inner Mongolia",
    "Jiangsu",
    "Jiangxi",
    "Jilin",
    "Liaoning",
    "Macau",
    "Ningxia",
    "Qinghai",
    "Shaanxi",
    "Shandong",
    "Shanghai",
    "Shanxi",
    "Sichuan",
    "Tianjin",
    "Tibet",
    "Xinjiang",
    "Yunnan",
    "Zhejiang",
  ],

  // Russia (federal subjects)
  RUS: [
    "Adygea",
    "Altai Republic",
    "Altai Krai",
    "Amur Oblast",
    "Arkhangelsk Oblast",
    "Astrakhan Oblast",
    "Bashkortostan",
    "Belgorod Oblast",
    "Bryansk Oblast",
    "Chechen Republic",
    "Chelyabinsk Oblast",
    "Chukotka AO",
    "Chuvashia",
    "Dagestan",
    "Ingushetia",
    "Irkutsk Oblast",
    "Ivanovo Oblast",
    "Jewish AO",
    "Kabardino-Balkaria",
    "Kaliningrad Oblast",
    "Kalmykia",
    "Kaluga Oblast",
    "Kamchatka Krai",
    "Karachay–Cherkessia",
    "Karelia",
    "Kemerovo Oblast",
    "Khabarovsk Krai",
    "Khakassia",
    "Khanty-Mansi AO",
    "Kirov Oblast",
    "Komi",
    "Kostroma Oblast",
    "Krasnodar Krai",
    "Krasnoyarsk Krai",
    "Kurgan Oblast",
    "Kursk Oblast",
    "Leningrad Oblast",
    "Lipetsk Oblast",
    "Magadan Oblast",
    "Mari El",
    "Mordovia",
    "Moscow",
    "Moscow Oblast",
    "Murmansk Oblast",
    "Nenets AO",
    "Nizhny Novgorod Oblast",
    "North Ossetia–Alania",
    "Novgorod Oblast",
    "Novosibirsk Oblast",
    "Omsk Oblast",
    "Orel Oblast",
    "Orenburg Oblast",
    "Penza Oblast",
    "Perm Krai",
    "Primorsky Krai",
    "Pskov Oblast",
    "Rostov Oblast",
    "Ryazan Oblast",
    "Saint Petersburg",
    "Sakha Republic",
    "Sakhalin Oblast",
    "Samara Oblast",
    "Saratov Oblast",
    "Smolensk Oblast",
    "Stavropol Krai",
    "Sverdlovsk Oblast",
    "Tambov Oblast",
    "Tatarstan",
    "Tomsk Oblast",
    "Tula Oblast",
    "Tuva",
    "Tver Oblast",
    "Tyumen Oblast",
    "Udmurtia",
    "Ulyanovsk Oblast",
    "Vladimir Oblast",
    "Volgograd Oblast",
    "Vologda Oblast",
    "Voronezh Oblast",
    "Yamalo-Nenets AO",
    "Yaroslavl Oblast",
    "Zabaykalsky Krai",
  ],
};
export default countryStateData;
